name: compile latex template and cv file
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 1 1 0'
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v4
        with:
          working_directory: ./main
          root_file: resume.tex
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main/resume.pdf
          if-no-files-found: error
      - name: push build files
        run: |
          sudo apt-get update && sudo apt-get install poppler-utils
          mv main/resume.pdf out/resume.pdf
          pdftoppm -png -f 1 -l 1 -r 450 out/resume.pdf out/resumeimg
          git config --global user.name "githubAction"
          git config --global user.email "actions@users.noreply.github.com"
          git add out/resume.pdf out/resumeimg-1.png
          git commit -m "updated at $(date +"%D %T")"          
          git push
